// More active effects for the Active effects card (added to BUFFS in effects.js): spells, conferred class abilities,
// worn items, combat modifiers and the rest of the Core Rulebook's conditions. Each one's numbers come from its rules
// text in the data (spells.json, magic-items.json, classes.json, talents.json); `ref` names that entry, and
// scripts/check_effects.py checks each number appears in it.
//
// Entry fields (see BUFFS in effects.js): bonuses(amount, mods) -> [{ target, type, value }] (mods: ability modifiers,
// for smite's +Cha); `scales`/`levelName` (a caster or class level), `levels` (amounts to pick), `forms` (a choice of
// forms, each { label, bonuses, size }: a polymorph's form sets your size), `flags`, `note`, `group`.

const b = (target, type, value) => ({ target, type, value });
const sk = (skill, type, value) => b(`skill:${skill}`, type, value);
const per = (cl, every, max, start = 1) => Math.min(max, Math.max(start, Math.floor(cl / every)));
const KNOWLEDGE = ['arcana', 'dungeoneering', 'engineering', 'geography', 'history', 'local', 'nature', 'nobility', 'planes', 'religion']
  .map(k => `Knowledge (${k})`);
const CHA_SKILLS = ['Bluff', 'Diplomacy', 'Disguise', 'Handle Animal', 'Intimidate', 'Perform', 'Use Magic Device'];
const form = (label, size, bonuses) => ({ label, size, bonuses });
// "Str +2" style pieces for forms.
const sz = (ab, n) => b(ab, n < 0 ? 'untyped' : 'size', n);
const na = n => b('ac', 'natural armor', n);

// Polymorph forms shared by several spells (Core Rulebook, Ultimate Magic).
const ANIMAL = {
  dim: form('Diminutive animal', 'Diminutive', [sz('dex', 6), sz('str', -4), na(1)]),
  tiny: form('Tiny animal', 'Tiny', [sz('dex', 4), sz('str', -2), na(1)]),
  small: form('Small animal', 'Small', [sz('dex', 2), na(1)]),
  medium: form('Medium animal', 'Medium', [sz('str', 2), na(2)]),
  large: form('Large animal', 'Large', [sz('str', 4), sz('dex', -2), na(4)]),
  huge: form('Huge animal', 'Huge', [sz('str', 6), sz('dex', -4), na(6)]),
  smallBeast: form('Small magical beast', 'Small', [sz('dex', 4), na(2)]),
  mediumBeast: form('Medium magical beast', 'Medium', [sz('str', 4), na(4)]),
  tinyBeast: form('Tiny magical beast', 'Tiny', [sz('str', -2), sz('dex', 8), na(3)]),
  largeBeast: form('Large magical beast', 'Large', [sz('str', 6), sz('dex', -2), sz('con', 2), na(6)]),
};
// Same sizes for other creature types (monstrous physique, undead anatomy).
const kindForms = (kind, sizes) => sizes.map(k => ({ ...ANIMAL[k], label: ANIMAL[k].label.replace('animal', kind) }));
const ELEMENTS = (size, air, earth, fire, water) => [form(`${size} air elemental`, size, air), form(`${size} earth elemental`, size, earth),
  form(`${size} fire elemental`, size, fire), form(`${size} water elemental`, size, water)];
// `also`: the earlier spells of a series whose forms it includes ("as beast shape III, except...").
const poly = (id, name, forms, ref, note = '', also = []) => ({ id, name, forms, ref: { spell: ref || name, also },
  note: note || 'natural attacks, movement and senses of the form (see the spell)' });
const spell = (id, name, bonuses, extra = {}) => ({ id, name, bonuses: typeof bonuses === 'function' ? bonuses : () => bonuses, ref: { spell: extra.refName || name }, ...extra });
const item = (id, name, bonuses, extra = {}) => ({ id, name, group: 'item', bonuses: typeof bonuses === 'function' ? bonuses : () => bonuses, ref: { item: extra.refName || name, ...(extra.refId ? { id: extra.refId } : {}) }, ...extra });
const ability = (id, name, bonuses, extra = {}) => ({ id, name, group: 'ability', bonuses: typeof bonuses === 'function' ? bonuses : () => bonuses, ...extra });

export const MORE_BUFFS = [
  // ---------------- Spells (Core Rulebook first, then later books) ----------------
  poly('alter-self', 'Alter self', [form('Small humanoid', 'Small', [sz('dex', 2)]), form('Medium humanoid', 'Medium', [sz('str', 2)])], 'Alter Self', 'the form’s movement and senses (see the spell)'),
  poly('beast-shape-1', 'Beast shape I', [ANIMAL.small, ANIMAL.medium], 'Beast Shape I'),
  poly('beast-shape-2', 'Beast shape II', [ANIMAL.tiny, ANIMAL.small, ANIMAL.medium, ANIMAL.large], 'Beast Shape II'),
  poly('beast-shape-3', 'Beast shape III', [ANIMAL.dim, ANIMAL.tiny, ANIMAL.small, ANIMAL.medium, ANIMAL.large, ANIMAL.huge, ANIMAL.smallBeast, ANIMAL.mediumBeast], 'Beast Shape III'),
  poly('beast-shape-4', 'Beast shape IV', [ANIMAL.dim, ANIMAL.tiny, ANIMAL.small, ANIMAL.medium, ANIMAL.large, ANIMAL.huge, ANIMAL.tinyBeast, ANIMAL.smallBeast, ANIMAL.mediumBeast, ANIMAL.largeBeast], 'Beast Shape IV', '', ['Beast Shape III']),
  poly('elemental-body-1', 'Elemental body I', ELEMENTS('Small', [sz('dex', 2), na(2)], [sz('str', 2), na(4)], [sz('dex', 2), na(2)], [sz('con', 2), na(4)]), 'Elemental Body I'),
  poly('elemental-body-2', 'Elemental body II', ELEMENTS('Medium', [sz('dex', 4), na(3)], [sz('str', 4), na(5)], [sz('dex', 4), na(3)], [sz('con', 4), na(5)]), 'Elemental Body II'),
  poly('elemental-body-3', 'Elemental body III', ELEMENTS('Large', [sz('str', 2), sz('dex', 4), na(4)], [sz('str', 6), sz('dex', -2), sz('con', 2), na(6)],
    [sz('dex', 4), sz('con', 2), na(4)], [sz('str', 2), sz('dex', -2), sz('con', 6), na(6)]), 'Elemental Body III'),
  poly('elemental-body-4', 'Elemental body IV', ELEMENTS('Huge', [sz('str', 4), sz('dex', 6), na(4)], [sz('str', 8), sz('dex', -2), sz('con', 4), na(6)],
    [sz('dex', 6), sz('con', 4), na(4)], [sz('str', 4), sz('dex', -2), sz('con', 8), na(6)]), 'Elemental Body IV'),
  poly('giant-form-1', 'Giant form I', [form('Large giant', 'Large', [sz('str', 6), sz('dex', -2), sz('con', 4), na(4)])], 'Giant Form I'),
  poly('giant-form-2', 'Giant form II', [form('Huge giant', 'Huge', [sz('str', 8), sz('dex', -2), sz('con', 6), na(6), b('speed', 'enhancement', 10)])], 'Giant Form II'),
  poly('form-of-the-dragon-1', 'Form of the dragon I', [form('Large dragon', 'Large', [sz('str', 4), sz('con', 2), na(4)])], 'Form of the Dragon I', 'fly 60 ft., breath weapon, resistance to one element'),
  poly('form-of-the-dragon-2', 'Form of the dragon II', [form('Huge dragon', 'Huge', [sz('str', 6), sz('con', 4), na(6)])], 'Form of the Dragon II', 'fly 90 ft., breath weapon, DR 5/magic, resistance'),
  poly('form-of-the-dragon-3', 'Form of the dragon III', [form('Huge dragon', 'Huge', [sz('str', 10), sz('con', 8), na(8)])], 'Form of the Dragon III', 'fly 120 ft., breath weapon, DR 10/magic, immunity to one element'),
  poly('plant-shape-1', 'Plant shape I', [form('Small plant', 'Small', [sz('con', 2), na(2)]), form('Medium plant', 'Medium', [sz('str', 2), b('con', 'enhancement', 2), na(2)])], 'Plant Shape I'),
  poly('plant-shape-2', 'Plant shape II', [form('Small plant', 'Small', [sz('con', 2), na(2)]), form('Medium plant', 'Medium', [sz('str', 2), b('con', 'enhancement', 2), na(2)]),
    form('Large plant', 'Large', [sz('str', 4), sz('con', 2), na(4)])], 'Plant Shape II'),
  poly('plant-shape-3', 'Plant shape III', [form('Small plant', 'Small', [sz('con', 2), na(2)]), form('Medium plant', 'Medium', [sz('str', 2), b('con', 'enhancement', 2), na(2)]),
    form('Large plant', 'Large', [sz('str', 4), sz('con', 2), na(4)]), form('Huge plant', 'Huge', [sz('str', 8), sz('dex', -2), sz('con', 4), na(6)])], 'Plant Shape III'),
  // Animal growth (animals only: an animal companion): a size bigger, +8 Str and +4 Con (size), -2 Dex, natural armor +2.
  spell('animal-growth', 'Animal growth', [sz('str', 8), sz('con', 4), sz('dex', -2), b('ac', 'natural armor enhancement', 2)],
        { size: 1, note: 'Animals only (an animal companion): its existing natural armor +2; speed unchanged' }),
  spell('righteous-might', 'Righteous might', [sz('str', 4), sz('con', 4), sz('dex', -2), b('ac', 'natural armor enhancement', 2)], { size: 1, note: 'DR 5 (10 at 15th) against evil or good' }),
  spell('iron-body', 'Iron body', [b('str', 'enhancement', 6), b('dex', 'untyped', -6)], { flags: ['halfSpeed'], note: '35% arcane spell failure and −6 check penalty as full plate; DR 15/adamantine; many immunities' }),
  spell('transformation', 'Transformation', [b('str', 'enhancement', 4), b('dex', 'enhancement', 4), b('con', 'enhancement', 4), b('ac', 'natural armor', 4), b('fort', 'competence', 5)],
    { note: 'your base attack bonus equals your character level; proficiency with simple and martial weapons; you can’t cast spells' }),
  spell('foresight', 'Foresight', [b('ac', 'insight', 2), b('ref', 'insight', 2)], { note: 'you’re never surprised or flat-footed' }),
  spell('heroes-feast', "Heroes' feast", [b('attack', 'morale', 1), b('will', 'morale', 1)], { note: '+4 morale on saves against poison and fear; 1d8 + ½ caster level temporary hit points (add them with Xtra-HP)' }),
  spell('holy-aura', 'Holy aura', [b('ac', 'deflection', 4), b('saves', 'resistance', 4)], { note: 'against evil creatures’ attacks and effects; also spell resistance 25' }),
  spell('unholy-aura', 'Unholy aura', [b('ac', 'deflection', 4), b('saves', 'resistance', 4)], { note: 'against good creatures’ attacks and effects; also spell resistance 25' }),
  spell('shield-of-law', 'Shield of law', [b('ac', 'deflection', 4), b('saves', 'resistance', 4)], { note: 'against chaotic creatures’ attacks and effects; also spell resistance 25' }),
  spell('cloak-of-chaos', 'Cloak of chaos', [b('ac', 'deflection', 4), b('saves', 'resistance', 4)], { note: 'against lawful creatures’ attacks and effects; also spell resistance 25' }),
  spell('dispel-evil', 'Dispel evil', [b('ac', 'deflection', 4)], { note: 'against evil creatures’ attacks' }),
  spell('protection-from-spells', 'Protection from spells', [b('saves', 'resistance', 8)], { note: 'only against spells and spell-like abilities' }),
  spell('shield-other', 'Shield other', [b('ac', 'deflection', 1), b('saves', 'resistance', 1)], { note: 'the caster takes half of the damage dealt to you' }),
  spell('death-knell', 'Death knell', [b('str', 'enhancement', 2)], { note: '1d8 temporary hit points and +1 effective caster level' }),
  spell('holy-sword', 'Holy sword', [b('attack', 'enhancement', 5), b('damage', 'enhancement', 5)], { note: 'on the paladin’s weapon; it becomes holy (+2d6 against evil)' }),
  spell('shillelagh', 'Shillelagh', [b('attack', 'enhancement', 1), b('damage', 'enhancement', 1)], { note: 'on your club or quarterstaff, which also deals damage as two sizes larger' }),
  spell('magic-fang', 'Magic fang', [b('attack', 'enhancement', 1), b('damage', 'enhancement', 1)], { note: 'one natural weapon or unarmed strike only' }),
  spell('greater-magic-fang', 'Greater magic fang', cl => [b('attack', 'enhancement', per(cl, 4, 5)), b('damage', 'enhancement', per(cl, 4, 5))],
    { scales: true, refName: 'Magic Fang, Greater', note: 'one natural weapon or unarmed strike only' }),
  spell('jump', 'Jump', cl => [sk('Acrobatics', 'enhancement', cl >= 9 ? 30 : cl >= 5 ? 20 : 10)], { scales: true, note: 'only on Acrobatics checks to jump' }),
  spell('ablative-barrier', 'Ablative barrier', [b('ac', 'armor', 2)], { note: 'turns 5 lethal damage into nonlethal per hit, up to 5 per caster level' }),
  spell('acute-senses', 'Acute senses', cl => [sk('Perception', 'enhancement', cl >= 16 ? 30 : cl >= 8 ? 20 : 10)], { scales: true }),
  spell('aspect-of-the-bear', 'Aspect of the bear', [b('ac', 'natural armor enhancement', 2), b('cmb', 'enhancement', 2)], { note: '+2 on bull rush, grapple and overrun checks (CMB here)' }),
  spell('aspect-of-the-falcon', 'Aspect of the falcon', [sk('Perception', 'competence', 3), b('ranged-attack', 'competence', 1)], { note: 'bows and crossbows threaten 19-20 ×3' }),
  spell('aspect-of-the-stag', 'Aspect of the stag', [b('speed', 'enhancement', 20)], { note: '+2 dodge AC against attacks of opportunity' }),
  spell('aspect-of-the-wolf', 'Aspect of the wolf', [b('str', 'enhancement', 4), b('dex', 'enhancement', 4)], { note: 'scent; +2 on trip attempts and trip as a swift action' }),
  { id: 'blessing-of-fervor', name: 'Blessing of fervor', ref: { spell: 'Blessing of Fervor' }, note: 'each round, choose one benefit',
    forms: [form('+2 attack, +2 dodge AC and Reflex', null, [b('attack', 'untyped', 2), b('ac', 'dodge', 2), b('ref', 'dodge', 2)]),
            form('+30 ft. speed', null, [b('speed', 'enhancement', 30)]), form('One extra attack (full attack)', null, []),
            form('Stand up as a swift action', null, []), form('Cast a spell as if with a metamagic feat', null, [])] },
  spell('blessing-of-the-mole', 'Blessing of the mole', [sk('Stealth', 'competence', 2)], { note: 'darkvision 30 ft.' }),
  spell('blessing-of-the-salamander', 'Blessing of the salamander', [b('cmd', 'competence', 2)], { note: 'fast healing 2; +2 CMD against grapples only' }),
  spell('boiling-blood', 'Boiling blood', [b('str', 'morale', 2)], { note: 'for orcs and half-orcs (others take fire damage)' }),
  spell('certain-grip', 'Certain grip', [sk('Climb', 'competence', 4)], { note: '+4 also on Acrobatics to balance and CMD against bull rush, drag, reposition and trip' }),
  { ...spell('contagious-zeal', 'Contagious zeal', [b('attack', 'morale', 2), b('damage', 'morale', 2)]), note: '+4 morale on saves against fear; 1d6 temporary hit points' },
  { id: 'deadly-juggernaut', name: 'Deadly juggernaut', ref: { spell: 'Deadly Juggernaut' }, levels: [1, 2, 3, 4, 5], levelName: 'foes dropped',
    bonuses: n => [b('melee-attack', 'luck', n), b('melee-damage', 'luck', n)], note: 'also on Strength checks and Strength skills; DR 2/— per foe (max 10/—)' },
  spell('extreme-flexibility', 'Extreme flexibility', [b('ac', 'dodge', 1), sk('Escape Artist', 'circumstance', 4)], { note: '+4 on grapple checks and CMD against grapples' }),
  spell('heroic-invocation', 'Heroic invocation', [b('attack', 'morale', 4), b('damage', 'morale', 4)], { note: '2d8+4 temporary hit points; immune to fear and charm' }),
  spell('heightened-awareness', 'Heightened awareness', [sk('Perception', 'competence', 2)], { note: '+2 also on Knowledge checks you are trained in' }),
  spell('holy-whisper', 'Holy whisper', [b('attack', 'sacred', 2), b('damage', 'sacred', 2)], { note: 'good creatures, for 1 round' }),
  spell('keen-senses', 'Keen senses', [sk('Perception', 'competence', 2)], { note: 'low-light vision' }),
  spell('mental-barrier-1', 'Mental barrier I', [b('ac', 'shield', 4)], { refName: 'Mental Barrier I' }),
  spell('mental-barrier-2', 'Mental barrier II', [b('ac', 'shield', 6)], { refName: 'Mental Barrier II' }),
  spell('oath-of-peace', 'Oath of peace', [b('ac', 'sacred', 5), b('saves', 'sacred', 5)], { note: 'DR 10/evil; ends if you attack' }),
  spell('perceive-cues', 'Perceive cues', [sk('Perception', 'competence', 5), sk('Sense Motive', 'competence', 5)]),
  spell('stunning-barrier', 'Stunning barrier', [b('ac', 'deflection', 1), b('saves', 'resistance', 1)]),
  { id: 'threefold-aspect', name: 'Threefold aspect', ref: { spell: 'Threefold Aspect' },
    forms: [form('Young adult', null, [b('dex', 'enhancement', 2), b('con', 'enhancement', 2), b('wis', 'untyped', -2)]),
            form('Adult', null, [b('wis', 'enhancement', 2), b('int', 'enhancement', 2), b('dex', 'untyped', -2)]),
            form('Elderly', null, [b('wis', 'enhancement', 4), b('int', 'enhancement', 4), b('str', 'untyped', -2), b('dex', 'untyped', -2)])] },
  spell('unwilling-shield', 'Unwilling shield', [b('ac', 'luck', 1), b('saves', 'luck', 1)], { note: 'the target takes half of the damage dealt to you' }),
  spell('vengeful-outrage', 'Vengeful outrage', [b('str', 'morale', 6), b('con', 'morale', 6), b('will', 'morale', 3)], { note: 'when you fight the chosen enemy; immune to shaken and frightened' }),
  spell('ward-the-faithful', 'Ward the faithful', cl => { const n = cl >= 18 ? 4 : cl >= 12 ? 3 : 2; return [b('ac', 'deflection', n), b('saves', 'resistance', n)]; },
    { scales: true, note: 'for those who share the caster’s faith' }),
  spell('weapon-of-awe', 'Weapon of awe', [b('damage', 'sacred', 2)], { note: 'one weapon; a critical hit leaves the target shaken' }),
  spell('wrath', 'Wrath', cl => [b('attack', 'morale', per(cl, 3, 3)), b('damage', 'morale', per(cl, 3, 3))], { scales: true, note: 'against the designated creature only' }),
  spell('divine-vessel', 'Divine vessel', [sz('str', 6), sz('con', 6), na(3)], { setSize: 'Large', note: 'the aspect adds more (see the spell): DR 10, resistances, a fly speed' }),
  spell('frightful-aspect', 'Frightful aspect', [sz('str', 6), sz('con', 4), na(6)], { setSize: 'Large', note: 'DR 10/magic, spell resistance 10 + ½ caster level, frightful presence' }),
  poly('monstrous-physique-1', 'Monstrous physique I', kindForms('monstrous humanoid', ['small', 'medium']), 'Monstrous Physique I'),
  poly('monstrous-physique-2', 'Monstrous physique II', kindForms('monstrous humanoid', ['tiny', 'small', 'medium', 'large']), 'Monstrous Physique II', '', ['Monstrous Physique I']),
  poly('monstrous-physique-3', 'Monstrous physique III', kindForms('monstrous humanoid', ['dim', 'tiny', 'small', 'medium', 'large', 'huge']), 'Monstrous Physique III', '', ['Monstrous Physique I', 'Monstrous Physique II']),
  poly('undead-anatomy-1', 'Undead anatomy I', kindForms('undead', ['small', 'medium']), 'Undead Anatomy I'),
  poly('undead-anatomy-2', 'Undead anatomy II', kindForms('undead', ['tiny', 'small', 'medium', 'large']), 'Undead Anatomy II', '+4 on saves against mind-affecting effects, disease, poison, sleep and stunning', ['Undead Anatomy I']),
  poly('undead-anatomy-3', 'Undead anatomy III', kindForms('undead', ['dim', 'tiny', 'small', 'medium', 'large', 'huge']), 'Undead Anatomy III', '+8 on saves against mind-affecting effects, disease, poison, sleep and stunning', ['Undead Anatomy I', 'Undead Anatomy II']),
  poly('vermin-shape-1', 'Vermin shape I', [form('Small vermin', 'Small', [sz('dex', 2), na(2)]), form('Medium vermin', 'Medium', [sz('str', 2), na(3)])], 'Vermin Shape I',
    '+2 resistance on saves against mind-affecting effects'),
  poly('vermin-shape-2', 'Vermin shape II', [form('Tiny vermin', 'Tiny', [sz('dex', 4), sz('str', -2), na(1)]), form('Small vermin', 'Small', [sz('dex', 2), na(2)]),
    form('Medium vermin', 'Medium', [sz('str', 2), na(3)]), form('Large vermin', 'Large', [sz('str', 4), sz('dex', -2), na(5)])], 'Vermin Shape II', '+4 on saves against mind-affecting effects', ['Vermin Shape I']),

  // ---------------- Conferred abilities ----------------
  ability('smite-evil', 'Smite evil (paladin)', (l, m) => [b('attack', 'untyped', Math.max(0, m?.cha || 0)), b('damage', 'untyped', l), b('ac', 'deflection', Math.max(0, m?.cha || 0))],
    { scales: true, levelName: 'paladin level', ref: { cls: 'paladin', feature: 'Smite Evil' },
      note: 'only against the smitten evil creature (the first hit on an evil outsider, dragon or undead deals 2 × level); your Charisma bonus is used' }),
  ability('smite-good', 'Smite good (antipaladin)', (l, m) => [b('attack', 'untyped', Math.max(0, m?.cha || 0)), b('damage', 'untyped', l), b('ac', 'deflection', Math.max(0, m?.cha || 0))],
    { scales: true, levelName: 'antipaladin level', ref: { cls: 'antipaladin', feature: 'Smite Good' }, note: 'only against the smitten good creature; your Charisma bonus is used' }),
  ability('divine-bond-weapon', 'Divine bond: weapon (paladin)', l => { const n = l < 5 ? 0 : Math.min(5, 1 + Math.floor((l - 5) / 3)); return [b('attack', 'enhancement', n), b('damage', 'enhancement', n)]; },
    { scales: true, levelName: 'paladin level', ref: { cls: 'paladin', feature: 'Divine Bond' }, note: 'on the bonded weapon; up to +6 at 20th (above +5 only as special abilities)' }),
  ability('arcane-pool-weapon', 'Arcane pool: weapon (magus)', l => { const n = Math.min(5, 1 + Math.floor((l - 1) / 4)); return [b('attack', 'enhancement', n), b('damage', 'enhancement', n)]; },
    { scales: true, levelName: 'magus level', ref: { cls: 'magus', feature: 'Arcane Pool' }, note: 'on the weapon you hold; can be spent on special abilities instead' }),
  ability('sacred-weapon', 'Sacred weapon (warpriest)', l => { const n = l < 4 ? 0 : Math.min(5, 1 + Math.floor((l - 4) / 4)); return [b('attack', 'enhancement', n), b('damage', 'enhancement', n)]; },
    { scales: true, levelName: 'warpriest level', ref: { cls: 'warpriest', feature: 'Sacred Weapon' }, note: 'on your sacred weapon' }),
  ability('sacred-armor', 'Sacred armor (warpriest)', l => [b('ac', 'enhancement', l < 7 ? 0 : Math.min(5, 1 + Math.floor((l - 7) / 3)))],
    { scales: true, levelName: 'warpriest level', ref: { cls: 'warpriest', feature: 'Sacred Armor' }, note: 'an enhancement bonus on your armor (doesn’t add to its own: the higher counts)' }),
  ability('judgment-destruction', 'Judgment: destruction (inquisitor)', l => [b('damage', 'sacred', 1 + Math.floor(l / 3))], { scales: true, levelName: 'inquisitor level', ref: { cls: 'inquisitor', feature: 'Judgment' }, note: 'weapon damage; profane if evil' }),
  ability('judgment-justice', 'Judgment: justice (inquisitor)', l => [b('attack', 'sacred', 1 + Math.floor(l / 5))], { scales: true, levelName: 'inquisitor level', ref: { cls: 'inquisitor', feature: 'Judgment' }, note: 'doubled to confirm critical hits from 10th' }),
  ability('judgment-protection', 'Judgment: protection (inquisitor)', l => [b('ac', 'sacred', 1 + Math.floor(l / 5))], { scales: true, levelName: 'inquisitor level', ref: { cls: 'inquisitor', feature: 'Judgment' } }),
  ability('judgment-purity', 'Judgment: purity (inquisitor)', l => [b('saves', 'sacred', 1 + Math.floor(l / 5))], { scales: true, levelName: 'inquisitor level', ref: { cls: 'inquisitor', feature: 'Judgment' }, note: 'doubled against curses, diseases and poisons from 10th' }),
  ability('judgment-other', 'Judgment: healing, piercing, resiliency or resistance (inquisitor)', [], { ref: { cls: 'inquisitor', feature: 'Judgment' },
    note: 'fast healing, a bonus on concentration and caster level checks, DR or energy resistance (see the class)' }),
  ability('bane', 'Bane (inquisitor)', [b('attack', 'enhancement', 2), b('damage', 'enhancement', 2)], { ref: { item: 'Bane' }, note: 'against the chosen creature type: the weapon is +2 better and deals +2d6 damage' }),
  ability('mutagen', 'Mutagen (alchemist)', [], { ref: { cls: 'alchemist', feature: 'Mutagen' },
    forms: [form('Strength', null, [b('str', 'alchemical', 4), b('int', 'untyped', -2), na(2)]), form('Dexterity', null, [b('dex', 'alchemical', 4), b('wis', 'untyped', -2), na(2)]),
            form('Constitution', null, [b('con', 'alchemical', 4), b('cha', 'untyped', -2), na(2)])] }),
  ability('greater-mutagen', 'Greater mutagen (alchemist)', [], { ref: { talent: 'Greater Mutagen' }, note: 'a −2 penalty to the two matching mental scores',
    forms: [['str', 'dex', 'int', 'wis'], ['str', 'con', 'int', 'cha'], ['dex', 'str', 'wis', 'int'], ['dex', 'con', 'wis', 'cha'], ['con', 'str', 'cha', 'int'], ['con', 'dex', 'cha', 'wis']]
      .map(([a, c, p, q]) => form(`${a[0].toUpperCase()}${a.slice(1)} +6, ${c[0].toUpperCase()}${c.slice(1)} +4`, null,
        [b(a, 'alchemical', 6), b(c, 'alchemical', 4), b(p, 'untyped', -2), b(q, 'untyped', -2), na(4)])) }),
  ability('grand-mutagen', 'Grand mutagen (alchemist)', [], { ref: { talent: 'Grand Mutagen' }, note: '−2 to Intelligence, Wisdom and Charisma',
    forms: [['str', 'dex', 'con'], ['str', 'con', 'dex'], ['dex', 'str', 'con'], ['dex', 'con', 'str'], ['con', 'str', 'dex'], ['con', 'dex', 'str']]
      .map(([x, y, z]) => form(`${x} +8, ${y} +6, ${z} +4`, null, [b(x, 'alchemical', 8), b(y, 'alchemical', 6), b(z, 'alchemical', 4),
        b('int', 'untyped', -2), b('wis', 'untyped', -2), b('cha', 'untyped', -2), na(6)])) }),
  ability('cognatogen', 'Cognatogen (alchemist)', [], { ref: { talent: 'Cognatogen', with: { cls: 'alchemist', feature: 'Mutagen' } }, note: 'a discovery: like a mutagen for a mental score',
    forms: [form('Intelligence', null, [b('int', 'alchemical', 4), b('str', 'untyped', -2), na(2)]), form('Wisdom', null, [b('wis', 'alchemical', 4), b('dex', 'untyped', -2), na(2)]),
            form('Charisma', null, [b('cha', 'alchemical', 4), b('con', 'untyped', -2), na(2)])] }),
  ...[['bear', 'Bear', l => [b('con', 'enhancement', l >= 15 ? 6 : l >= 8 ? 4 : 2)]], ['bull', 'Bull', l => [b('str', 'enhancement', l >= 15 ? 6 : l >= 8 ? 4 : 2)]],
      ['falcon', 'Falcon', l => [sk('Perception', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]], ['frog', 'Frog', l => [sk('Swim', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]],
      ['monkey', 'Monkey', l => [sk('Climb', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]], ['owl', 'Owl', l => [sk('Stealth', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]]]
    .map(([id, name, fn]) => ability(`animal-focus-${id}`, `Animal focus: ${name.toLowerCase()} (hunter)`, fn, { scales: true, levelName: 'hunter level', ref: { cls: 'hunter', feature: 'Animal Focus' },
      ...(id === 'frog' ? { note: 'the same bonus on Acrobatics checks to jump' } : {}) })),
  ...[['bear', 'Bear', l => [b('con', 'enhancement', l >= 15 ? 6 : l >= 8 ? 4 : 2)]], ['bull', 'Bull', l => [b('str', 'enhancement', l >= 15 ? 6 : l >= 8 ? 4 : 2)]],
      ['tiger', 'Tiger', l => [b('dex', 'enhancement', l >= 15 ? 6 : l >= 8 ? 4 : 2)]], ['deinonychus', 'Deinonychus', l => [b('init', 'untyped', l >= 15 ? 6 : l >= 8 ? 4 : 2)]],
      ['falcon', 'Falcon', l => [sk('Perception', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]], ['frog', 'Frog', l => [sk('Swim', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]],
      ['lizard', 'Lizard', l => [sk('Acrobatics', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]], ['monkey', 'Monkey', l => [sk('Climb', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]],
      ['owl', 'Owl', l => [sk('Stealth', 'competence', l >= 15 ? 8 : l >= 8 ? 6 : 4)]], ['stag', 'Stag', l => [b('speed', 'enhancement', l >= 15 ? 20 : l >= 8 ? 10 : 5)]]]
    .map(([id, name, fn]) => ability(`shifter-${id}`, `${name} aspect, minor form (shifter)`, fn, { scales: true, levelName: 'shifter level', ref: { talent: `${name} Aspect` } })),
  ability('studied-combat', 'Studied combat (investigator)', l => [b('melee-attack', 'insight', Math.floor(l / 2)), b('melee-damage', 'untyped', Math.floor(l / 2))],
    { scales: true, levelName: 'investigator level', ref: { cls: 'investigator', feature: 'Studied Combat' }, note: 'only against the studied creature; the damage is precision damage' }),
  ability('quarry', 'Quarry (ranger)', l => [b('attack', 'insight', l >= 19 ? 4 : 2)], { scales: true, levelName: 'ranger level', ref: { cls: 'ranger', feature: 'Quarry' },
    note: 'against your quarry; critical threats confirm automatically (improved quarry at 19th: +4)' }),
  ability('favored-terrain', 'Favored terrain (ranger)', n => [b('init', 'untyped', n), ...['Knowledge (geography)', 'Perception', 'Stealth', 'Survival'].map(s => sk(s, 'untyped', n))],
    { levels: [2, 4, 6, 8, 10], levelName: 'bonus', ref: { cls: 'ranger', feature: 'Favored Terrain' }, note: 'while in that terrain' }),
  ability('cavalier-banner', "Banner (cavalier)", l => [b('melee-attack', 'morale', 1 + Math.max(0, Math.floor((l - 5) / 5)))],
    { scales: true, levelName: 'cavalier level', ref: { cls: 'cavalier', feature: 'Banner' }, note: 'only on attacks made as part of a charge; +2 (and up) morale on saves against fear' }),
  ability('ki-defense', 'Ki: +4 dodge AC (monk)', [b('ac', 'dodge', 4)], { ref: { cls: 'monk', feature: 'Ki Pool' }, note: 'for 1 round (1 ki point, swift action)' }),
  ability('dodging-panache', 'Dodging panache (swashbuckler)', (l, m) => [b('ac', 'dodge', Math.max(0, m?.cha || 0))], { ref: { cls: 'swashbuckler', feature: 'Deeds' },
    note: 'against one melee attack (1 panache point); your Charisma bonus is used' }),
  ability('swashbuckler-initiative', 'Swashbuckler initiative', [b('init', 'untyped', 2)], { ref: { cls: 'swashbuckler', feature: 'Deeds' }, note: 'while you have at least 1 panache point' }),
  ability('gunslinger-initiative', 'Gunslinger initiative', [b('init', 'untyped', 2)], { ref: { cls: 'gunslinger', feature: 'Deeds' }, note: 'while you have at least 1 grit point' }),
  ability('ward-hex', 'Ward (witch hex)', l => { const n = 2 + (l >= 8 ? 1 : 0) + (l >= 16 ? 1 : 0); return [b('ac', 'deflection', n), b('saves', 'resistance', n)]; },
    { scales: true, levelName: 'witch level', ref: { talent: 'Ward' }, note: 'until the warded creature is hit or fails a save' }),
  ability('battlecry', 'Battlecry (oracle revelation)', l => { const n = l >= 10 ? 2 : 1; return [b('attack', 'morale', n), b('skills', 'morale', n), b('saves', 'morale', n)]; },
    { scales: true, levelName: 'oracle level', ref: { talent: 'Battlecry' } }),

  // ---------------- Other adjustments: worn items ----------------
  ...[['str', 'dex'], ['str', 'con'], ['dex', 'con']].map(([x, y]) => ({ id: `belt-physical-might-${x}-${y}`, name: `Belt of physical might (${x} and ${y})`, group: 'item',
    levels: [2, 4, 6], levelName: 'bonus', bonuses: n => [b(x, 'enhancement', n), b(y, 'enhancement', n)], ref: { item: 'Belt of Physical Might' } })),
  { id: 'belt-physical-perfection', name: 'Belt of physical perfection', group: 'item', levels: [2, 4, 6], levelName: 'bonus',
    bonuses: n => ['str', 'dex', 'con'].map(x => b(x, 'enhancement', n)), ref: { item: 'Belt of Physical Perfection' } },
  ...[['int', 'wis'], ['int', 'cha'], ['wis', 'cha']].map(([x, y]) => ({ id: `headband-mental-prowess-${x}-${y}`, name: `Headband of mental prowess (${x} and ${y})`, group: 'item',
    levels: [2, 4, 6], levelName: 'bonus', bonuses: n => [b(x, 'enhancement', n), b(y, 'enhancement', n)], ref: { item: 'Headband of Mental Prowess' } })),
  { id: 'headband-mental-superiority', name: 'Headband of mental superiority', group: 'item', levels: [2, 4, 6], levelName: 'bonus',
    bonuses: n => ['int', 'wis', 'cha'].map(x => b(x, 'enhancement', n)), ref: { item: 'Headband of Mental Superiority' } },
  item('ioun-dusty-rose', 'Ioun stone: dusty rose prism', [b('ac', 'insight', 1)], { refName: 'Ioun Stones' }),
  item('ioun-deep-red', 'Ioun stone: deep red sphere', [b('dex', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-incandescent-blue', 'Ioun stone: incandescent blue sphere', [b('wis', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-pale-blue', 'Ioun stone: pale blue rhomboid', [b('str', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-pink', 'Ioun stone: pink rhomboid', [b('con', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-pink-and-green', 'Ioun stone: pink and green sphere', [b('cha', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-scarlet-and-blue', 'Ioun stone: scarlet and blue sphere', [b('int', 'enhancement', 2)], { refName: 'Ioun Stones' }),
  item('ioun-pale-green', 'Ioun stone: pale green prism', [b('d20', 'competence', 1)], { refName: 'Ioun Stones', note: 'attack rolls, saves, skill checks and ability checks' }),
  item('ioun-dark-blue', 'Ioun stone: dark blue rhomboid (Alertness)', [sk('Perception', 'untyped', 2), sk('Sense Motive', 'untyped', 2)], { refName: 'Ioun Stones', note: '+4 with 10 or more ranks' }),
  item('stone-of-good-luck', 'Stone of good luck (luckstone)', [b('saves', 'luck', 1), b('skills', 'luck', 1), b('checks', 'luck', 1)], { refName: 'Stone of Good Luck' }),
  item('ring-of-force-shield', 'Ring of force shield', [b('ac', 'shield', 2)], { note: 'as a heavy shield with no check penalty or spell failure' }),
  item('robe-of-the-archmagi', 'Robe of the archmagi', [b('ac', 'armor', 5), b('saves', 'resistance', 4)], { note: 'spell resistance 18; +2 on caster level checks to beat spell resistance' }),
  item('staff-of-power', 'Staff of power', [b('ac', 'luck', 2), b('saves', 'luck', 2)]),
  item('robe-of-stars', 'Robe of stars', [b('saves', 'luck', 1)]),
  item('jingasa', 'Jingasa of the fortunate soldier', [b('ac', 'luck', 1)], { refName: 'Jingasa of the Fortunate Soldier' }),
  item('vambraces-of-defense', 'Vambraces of defense', [b('ac', 'deflection', 1)]),
  item('charm-bracelet', 'Charm bracelet', [b('checks', 'luck', 2)]),
  item('headband-fortunes-favor', "Headband of fortune's favor", [b('saves', 'luck', 1)], { refName: "Headband of Fortune's Favor" }),
  item('veiled-eye', 'Veiled eye', [b('saves', 'insight', 2)]),
  item('bracers-of-archery-lesser', 'Bracers of archery, lesser', [b('ranged-attack', 'competence', 1)], { refName: 'Bracers of Archery, Lesser', note: 'with bows only' }),
  item('bracers-of-archery-greater', 'Bracers of archery, greater', [b('ranged-attack', 'competence', 2)], { refName: 'Bracers of Archery, Greater', note: 'with bows only; also +1 competence on damage with bows' }),
  ...[['boots-of-elvenkind', 'Boots of Elvenkind', [['Acrobatics', 5]]], ['cloak-of-elvenkind', 'Cloak of Elvenkind', [['Stealth', 5]]],
      ['eyes-of-the-eagle', 'Eyes of the Eagle', [['Perception', 5]]], ['goggles-of-minute-seeing', 'Goggles of Minute Seeing', [['Disable Device', 5]]],
      ['gloves-of-swimming-and-climbing', 'Gloves of Swimming and Climbing', [['Swim', 5], ['Climb', 5]]], ['ring-of-climbing', 'Ring of Climbing', [['Climb', 5]]],
      ['ring-of-swimming', 'Ring of Swimming', [['Swim', 5]]], ['vest-of-escape', 'Vest of Escape', [['Disable Device', 4], ['Escape Artist', 6]]],
      ['lens-of-detection', 'Lens of Detection', [['Perception', 5]]], ['robe-of-eyes', 'Robe of Eyes', [['Perception', 10]]], ['wings-of-flying', 'Wings of Flying', [['Fly', 5]]],
      ['cloak-of-the-bat', 'Cloak of the Bat', [['Stealth', 5]]], ['ring-of-chameleon-power', 'Ring of Chameleon Power', [['Stealth', 10]]],
      ['elixir-of-hiding', 'Elixir of Hiding', [['Stealth', 10]]], ['elixir-of-swimming', 'Elixir of Swimming', [['Swim', 10]]], ['elixir-of-tumbling', 'Elixir of Tumbling', [['Acrobatics', 10]]],
      ['elixir-of-vision', 'Elixir of Vision', [['Perception', 10]]], ['elixir-of-the-thundering-voice', 'Elixir of the Thundering Voice', [['Intimidate', 10]]],
      ['salve-of-slipperiness', 'Salve of Slipperiness', [['Escape Artist', 20]]], ['belt-of-tumbling', 'Belt of Tumbling', [['Acrobatics', 4]]], ['eagle-cape', 'Eagle Cape', [['Perception', 5]]],
      ['gloves-of-larceny', 'Gloves of Larceny', [['Sleight of Hand', 5]]], ['healers-gloves', "Healer's Gloves", [['Heal', 5]]], ['inquisitors-monocle', "Inquisitor's Monocle", [['Sense Motive', 5]]],
      ['stalkers-mask', "Stalker's Mask", [['Stealth', 5]]], ['horsemasters-saddle', "Horsemaster's Saddle", [['Ride', 5]]], ['misers-mask', "Miser's mask", [['Appraise', 5]]],
      ['glyphbane-gloves', 'Glyphbane Gloves', [['Disable Device', 5]]], ['darklands-goggles', 'Darklands Goggles', [['Perception', 4], ['Survival', 4]]],
      ['judges-wig', "Judge's Wig", [['Diplomacy', 4], ['Intimidate', 4]]], ['highwaymans-cape', "Highwayman's Cape", [['Bluff', 5], ['Stealth', 5]]],
      ['daredevil-boots', 'Daredevil Boots', [['Acrobatics', 5]]], ['helm-of-the-mammoth-lord', 'Helm of the Mammoth Lord', [['Handle Animal', 5]]],
      ['cloak-of-the-diplomat', 'Cloak of the Diplomat', [['Diplomacy', 5], ['Sense Motive', 5]]], ['crown-of-conquest', 'Crown of Conquest', [['Intimidate', 4]]]]
    .map(([id, ref, list]) => item(id, ref, list.map(([s, n]) => sk(s, 'competence', n)), { refName: ref,
      ...(id === 'lens-of-detection' ? { note: '+5 also on Survival checks to track' } : id === 'salve-of-slipperiness' ? { note: '+20 also on combat maneuver checks to escape a grapple' } : {}) })),
  item('ring-of-jumping', 'Ring of Jumping', [sk('Acrobatics', 'competence', 5)], { note: 'only on Acrobatics checks to jump' }),
  item('mask-of-a-thousand-tomes', 'Mask Of A Thousand Tomes', KNOWLEDGE.map(k => sk(k, 'competence', 10))),
  item('circlet-of-persuasion', 'Circlet of Persuasion', CHA_SKILLS.map(s => sk(s, 'competence', 3)), { note: 'also on Charisma checks' }),

  // More items with plain bonuses (the item's own name, so its row in Active effects finds it). `when`: the bonus only
  // applies sometimes (in a terrain, against one kind of attack, while the item is used): on the item's row in Active
  // effects it starts switched off, to tick when it applies.
  ...[
    // Abilities, AC, saves, initiative, speed.
    ['Belt of Mighty Hurling, Lesser', [b('str', 'enhancement', 2)], { note: 'Strength on thrown weapon attack rolls; +10 ft. range increment' }],
    ['Belt of Mighty Hurling, Greater', [b('str', 'enhancement', 4)], { note: 'thrown weapons return' }],
    ["Anaconda's Coils", [b('str', 'enhancement', 2)], { note: '+2 competence on grapple checks' }],
    ['Belt of Dwarvenkind', [b('con', 'enhancement', 2)], { note: 'darkvision, stonecunning, +2 resistance on saves against poison, spells and spell-like effects; Charisma checks with dwarves' }],
    ['Belt of the Weasel', [b('dex', 'enhancement', 2)]],
    ['Belt of Thunderous Charging', [b('str', 'enhancement', 2)]],
    ['Elemental Earth Belt', [b('con', 'enhancement', 4)]],
    ['Gorgon Belt', [b('str', 'enhancement', 4)]],
    ['Minotaur Belt', [b('str', 'enhancement', 2)]],
    ['Mirroring Belt', [b('dex', 'enhancement', 2)]],
    ['Monkey Belt', [b('dex', 'enhancement', 2)]],
    ['Monkey Belt, Greater', [b('str', 'enhancement', 2), b('dex', 'enhancement', 2)], { note: '+5 circumstance on Climb while it is a tail' }],
    ['Plague Rat Belt', [b('con', 'enhancement', 2)]],
    ['Plague Rat Belt, Greater', [b('dex', 'enhancement', 2), b('con', 'enhancement', 2)]],
    ['Serpent Belt, Greater', [b('str', 'enhancement', 2), b('dex', 'enhancement', 2)]],
    ['Shadowform Belt', [b('dex', 'enhancement', 6)]],
    ['Cord of Stubborn Resolve', [b('con', 'enhancement', 2)]],
    ['Headband of Mental Resilience', [b('int', 'enhancement', 2), b('wis', 'enhancement', 2), b('cha', 'enhancement', 2)]],
    ['Headband of Ponderous Recollection', [b('int', 'enhancement', 2)]],
    ['Headband of Sealed Thoughts', [b('int', 'enhancement', 4)]],
    ['Headband of Unshakeable Resolve', [b('wis', 'enhancement', 2)]],
    ['Rod of Splendor', [b('cha', 'enhancement', 4)]],
    ['Staff of Mithral Might', [b('int', 'enhancement', 2)]],
    ['Snakeskin Tunic', [b('ac', 'armor', 1), b('dex', 'enhancement', 2)], { note: '+2 resistance on saves against poison' }],
    ['Corset of Dire Witchcraft', [b('ac', 'armor', 4)]],
    ['Guardian Gorget', [b('ac', 'armor', 2)]],
    ["Gunman's Duster", [b('ac', 'armor', 4)], { note: '+2 luck to touch AC against firearms' }],
    ['Dragon Staff', [b('ac', 'natural armor', 2)], { note: 'a bite attack' }],
    ['Staff of the Hierophant', [b('ac', 'luck', 2), b('saves', 'luck', 2)]],
    ['Luck Blade', [b('saves', 'luck', 1)]],
    ['Belt of Fallen Heroes', [b('saves', 'insight', 1)]],
    ['Cape of Daring Deeds', [b('saves', 'resistance', 2)]],
    ['Cloak of Fangs', [b('saves', 'resistance', 1)]],
    ['Otherworldly Kimono', [b('saves', 'resistance', 4)], { note: '+4 on caster level checks' }],
    ["Penitent's Robes", [b('saves', 'resistance', 1)], { note: 'more with mythic vows' }],
    ['Resplendent Robe of the Thespian', [b('saves', 'resistance', 4)], { note: 'spell resistance 18' }],
    ['Wyvern Cloak', [b('will', 'resistance', 4)], { note: 'feather fall; fly once a day; a sting' }],
    ['Rod of Alertness', [b('init', 'insight', 1)]],
    ['Agile Alpenstock', [b('speed', 'enhancement', 5)], { note: '+2 to CMD and saves against trips' }],
    ['Staff of Travel', [b('speed', 'enhancement', 10)]],
    ["Juggernaut's Pauldrons", [b('cmd', 'untyped', 4)], { note: 'ferocity' }],
    ['Boneless Leather', [sk('Escape Artist', 'untyped', 5), b('cmd', 'untyped', 5)], { note: 'DR 5/piercing or slashing; +5 on Acrobatics to reduce falling damage' }],
    // Skills.
    ['Catskin Leather', [sk('Acrobatics', 'competence', 5)], { note: 'half damage from falling' }],
    ["Burglar's Buckler", [sk('Disable Device', 'competence', 2), sk('Sleight of Hand', 'competence', 2)], { note: 'dirty trick checks and CMD' }],
    ['Breastplate of Command', CHA_SKILLS.map(s => sk(s, 'competence', 2)), { note: 'also on Charisma checks' }],
    ['Hellscourge', [sk('Intimidate', 'competence', 5)]],
    ['Quarterstaff of Vaulting', [sk('Acrobatics', 'competence', 5)]],
    ['Ring of Tactical Precision', [sk('Profession', 'competence', 5)], { note: 'Profession (soldier) only; +1 to teamwork and aid another bonuses' }],
    ['Ring of the Ecclesiarch', [sk('Diplomacy', 'competence', 5), sk('Knowledge (religion)', 'competence', 5)]],
    ['Ring of the Sophisticate', [sk('Sense Motive', 'competence', 4), sk('Knowledge (local)', 'competence', 4)]],
    ["Scholar's Ring", [sk('Knowledge (history)', 'competence', 5)], { note: 'comprehend languages' }],
    ['Rod of Beguiling', [sk('Bluff', 'competence', 5), sk('Sleight of Hand', 'competence', 5)]],
    ['Suzerain Scepter', [sk('Diplomacy', 'competence', 5), sk('Knowledge (nobility)', 'competence', 5)]],
    ['Sapling Rod', [sk('Survival', 'competence', 5)], { note: 'on Survival to get along in the wild and not get lost' }],
    ['Aquatic Cummerbund', [sk('Swim', 'competence', 4)]],
    ['Bracers of the Glib Entertainer', [sk('Perform', 'competence', 5)]],
    ["Cackling Hag's Blouse", [sk('Intimidate', 'competence', 2)]],
    ['Claws of the Ice Bear', [sk('Climb', 'competence', 2)], { note: 'also Acrobatics using both hands' }],
    ['Cloak of the Sneaky Scoundrel', [sk('Stealth', 'competence', 5)]],
    ['Cloak of the Troll King', [sk('Intimidate', 'competence', 5)], { note: 'burning hands 3 times a day' }],
    ["Dead Man's Headband", [sk('Intimidate', 'competence', 2)], { note: '+1 DC of your fear effects' }],
    ['Eyes of Keen Sight', [sk('Perception', 'competence', 2)], { note: 'low-light vision' }],
    ['Gloves of Elvenkind', [sk('Spellcraft', 'competence', 5)], { note: 'also concentration checks to cast defensively' }],
    ["Hunter's Band", [sk('Survival', 'competence', 5)]],
    ['Lenses of Detection', [sk('Perception', 'competence', 5)]],
    ['Lion Cloak', [sk('Intimidate', 'circumstance', 2)], { note: '+2 resistance on saves against mind-affecting and fear effects' }],
    ['Living Garments', [sk('Diplomacy', 'competence', 5)]],
    ['Maw of the Wyrm', [sk('Intimidate', 'competence', 4)], { note: '+4 insight on saves against frightful presence' }],
    ['Mitre of the Hierophant', [sk('Diplomacy', 'competence', 5), sk('Knowledge (religion)', 'competence', 5)]],
    ["Pirate's Eye Patch", [sk('Swim', 'competence', 2), sk('Climb', 'competence', 2)]],
    ['Pliant Gloves', [sk('Escape Artist', 'enhancement', 5)], { note: 'also Acrobatics to avoid falling damage' }],
    ["Prestidigitator's Cloak", [sk('Sleight of Hand', 'competence', 8)]],
    ["Seducer's Bane", [sk('Sense Motive', 'competence', 5)], { note: '+5 resistance on Will saves against enchantments' }],
    ["Slayer's Robe", [sk('Stealth', 'competence', 5), b('saves', 'resistance', 1)]],
    ['Stole of Justice', [sk('Sense Motive', 'competence', 5)], { note: 'zone of truth' }],
    // Only sometimes: switched on when it applies.
    ['Stalking Armor', [sk('Stealth', 'competence', 5), sk('Perception', 'competence', 5)], { when: 'in its chosen terrain' }],
    ["Dragonslayer's Shield", [b('will', 'morale', 2)], { when: 'against frightful presence' }],
    ["Wyrmslayer's Shield", [b('will', 'morale', 6)], { when: 'against frightful presence' }],
    ['Spell Ward Tower Shield', [b('ref', 'resistance', 4)], { when: 'against spells and spell-like abilities' }],
    ['Rapier of Battlefield Movement', [sk('Acrobatics', 'competence', 5)], { when: "to move through threatened squares or a foe's space" }],
    ["Spider's Fang", [sk('Acrobatics', 'competence', 2)], { when: 'to move through threatened squares' }],
    ['Rod of Escape', [sk('Escape Artist', 'competence', 5)], { when: 'when tied up by nonmagical means' }],
    ['Staff of Accompaniment', [sk('Perform', 'competence', 2)], { when: 'with bardic performance' }],
    ['Dryad Sandals', [sk('Stealth', 'competence', 2)], { when: 'in forests' }],
    ['Stonemist Cloak', [sk('Stealth', 'competence', 5)], { when: 'in rocky or mountainous areas, hood up' }],
    ['Headband of Counterspelling', [sk('Spellcraft', 'insight', 5)], { when: 'to identify a spell as it is cast' }],
    ['Burglar Boots, Minor', [sk('Perception', 'competence', 5)], { when: 'to find traps and devices on the floor' }],
    ['Burglar Boots, Major', [sk('Perception', 'competence', 10), b('ref', 'competence', 10)], { when: 'against traps on the floor', note: '+10 competence to AC against those traps' }],
    ['Acrobat Slippers', [b('ref', 'competence', 2)], { when: 'on Reflex saves to avoid falling', note: '+2 CMD against trips' }],
    ["Hunter's Nose Ring", [sk('Perception', 'competence', 4), sk('Survival', 'competence', 4)], { when: 'by smell (Survival: tracking by scent)', note: 'scent' }],
    ['Darksire Amulet', [sk('Diplomacy', 'insight', 4)], { when: 'to influence evil outsiders' }],
    ['Boots of Vaulting', [sk('Acrobatics', 'competence', 10)], { when: 'to avoid attacks of opportunity while jumping, or to land' }],
    ['Daredevil Softpaws', [sk('Acrobatics', 'competence', 5)], { when: 'clicked on (10 rounds a day), to move past foes' }],
    ['Cape of Bravado', [b('ac', 'insight', 1)], { when: 'held over your arm', note: '+5 competence on Bluff to feint' }],
    ['Elixir of Forceful Exhalation', [sk('Swim', 'competence', 4)], { when: 'for 1 hour after drinking it', note: 'also Acrobatics to jump' }],
    ['Bottled Yeti Fur', [b('ac', 'natural armor', 2)], { when: 'for 24 hours after opening it', note: 'cold resistance 5; +4 Stealth in ice and snow' }],
    ['Bracers of the Shield Mates', [b('ac', 'shield', 2)], { when: 'while the two wearers are within 100 feet' }],
    // Armor and shield special abilities (on the armor or shield you wear).
    ['Amorphous', [sk('Escape Artist', 'competence', 5)], { note: '+5 CMD against grapples' }],
    ['Harmonizing', [sk('Perform', 'competence', 5), sk('Stealth', 'untyped', -5)], { note: 'vulnerable to sonic damage' }],
    ['Shadow', [sk('Stealth', 'competence', 5)]],
    ['Shadow, Improved', [sk('Stealth', 'competence', 10)]],
    ['Improved Shadow', [sk('Stealth', 'competence', 10)]],
    ['Shadow, Greater', [sk('Stealth', 'competence', 15)]],
    ['Slick', [sk('Escape Artist', 'competence', 5)]],
    ['Slick, Improved', [sk('Escape Artist', 'competence', 10)]],
    ['Improved Slick', [sk('Escape Artist', 'competence', 10)]],
    ['Slick, Greater', [sk('Escape Artist', 'competence', 15)]],
    ['Jousting', [sk('Ride', 'competence', 5)]],
    ['Trackless', [sk('Stealth', 'competence', 5)], { note: '-5 on Survival checks to track you' }],
    ['Champion', [b('ac', 'sacred', 2)], { when: 'against the foe you challenge or smite' }],
    ['Dastard', [b('ac', 'profane', 2)], { when: 'against the foe you challenge or smite' }],
    ['Spell Dodging', [b('ac', 'dodge', 4)], { when: 'against attacks from spells, spell-like abilities and summoned creatures' }],
    ['Expeditious', [b('speed', 'enhancement', 10)], { when: 'for 1 round when you summon it' }],
    ['Poison-Resistant', [b('saves', 'resistance', 3)], { when: 'against poison' }],
    ['Brawling', [b('attack', 'untyped', 2), b('damage', 'untyped', 2)], { refName: 'Brawling', refId: 'brawling-armor-and-shield-special-abilities', when: 'with unarmed strikes' }],
    // Weapon special abilities (while you wield the weapon).
    ['Dueling', [b('init', 'enhancement', 4)], { when: 'with the weapon drawn' }],
    ['Grounding', [b('saves', 'competence', 2)], { when: 'against air and electricity effects, wielding it' }],
    ['Neutralizing', [b('saves', 'competence', 2)], { when: 'against acid and earth effects, wielding it' }],
    ['Quenching', [b('saves', 'competence', 2)], { when: 'against fire effects, wielding it' }],
    ['Thawing', [b('saves', 'competence', 2)], { when: 'against ice effects, wielding it' }],
    ['Invigorating', [b('attack', 'morale', 2), b('speed', 'enhancement', 10)], { when: 'after it removes fatigue (see its text)' }],
  ].map(([name, list, extra = {}]) => item(`mi-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '')}`, name, list, extra)),

  // ---------------- Medium: the spirit bonus of the spirit channeled (+1, +1 at 4th and every 4 levels) ----------------
  ...[['archmage', 'archmage', ['Appraise', 'Craft', ...KNOWLEDGE, 'Linguistics', 'Spellcraft'], [], 'concentration checks and Intelligence checks'],
      ['champion', 'champion', ['Climb', 'Swim'], ['attack', 'damage', 'fort'], 'only non-spell damage; Strength checks'],
      ['guardian', 'guardian', [], ['ac', 'fort', 'ref'], 'Constitution checks'],
      ['hierophant', 'hierophant', ['Heal', 'Perception', 'Profession', 'Sense Motive', 'Survival'], ['will'], 'Wisdom checks'],
      ['marshal', 'marshal', CHA_SKILLS, [], 'Charisma checks and spirit surge rolls'],
      ['trickster', 'trickster', [], ['skills', 'ref'], 'Dexterity checks']]
    .map(([id, spirit, skills, targets, note]) => ability(`medium-spirit-${id}`, `Spirit bonus: ${spirit} (medium)`, lv => {
      const n = 1 + Math.floor(lv / 4);
      return [...skills.map(s => sk(s, 'untyped', n)), ...targets.map(t => b(t, 'untyped', n))];
    }, { scales: true, levelName: 'medium level', ref: { cls: 'medium', feature: 'Spirit Bonus' }, note: `also on ${note}` })),

  // ---------------- Circumstances ----------------
  { id: 'masterwork-tool', name: 'Masterwork tool', group: 'circumstance', bonuses: () => [b('skills', 'circumstance', 2)], note: 'on the skill the tool is for (all skills here)' },

  // ---------------- Combat modifiers (Core Rulebook Tables 8-5 and 8-6, and combat actions) ----------------
  { id: 'combat-expertise', name: 'Combat Expertise (feat)', group: 'combat', scales: true, levelName: 'base attack bonus',
    bonuses: bab => { const n = 1 + Math.floor(bab / 4); return [b('attack', 'untyped', -n), b('ac', 'dodge', n)]; }, note: 'melee attacks only; until your next turn' },
  { id: 'running', name: 'Running', group: 'combat', flags: ['noDexAc'], bonuses: () => [], note: 'you lose your Dex bonus to AC unless you have the Run feat' },
  { id: 'kneeling', name: 'Kneeling or sitting', group: 'combat', bonuses: () => [], note: '−2 AC against melee attacks, +2 against ranged attacks' },
  { id: 'concealment', name: 'Concealment', group: 'combat', bonuses: () => [], note: 'attacks against you have a 20% miss chance' },
  { id: 'total-concealment', name: 'Total concealment', group: 'combat', bonuses: () => [], note: 'attacks against you have a 50% miss chance; foes must guess your square' },
  { id: 'mounted-ranged-double', name: 'Ranged attack from a mount (double move)', group: 'combat', bonuses: () => [b('ranged-attack', 'untyped', -4)] },
  { id: 'mounted-ranged-run', name: 'Ranged attack from a mount (running)', group: 'combat', bonuses: () => [b('ranged-attack', 'untyped', -8)] },
  { id: 'improvised-weapon', name: 'Improvised weapon', group: 'combat', bonuses: () => [b('attack', 'untyped', -4)], note: 'unless you have Catch Off-Guard or Throw Anything' },
  { id: 'nonlethal-with-lethal', name: 'Nonlethal damage with a lethal weapon', group: 'combat', bonuses: () => [b('attack', 'untyped', -4)] },
  { id: 'target-helpless', name: 'Target is helpless', group: 'combat', bonuses: () => [b('melee-attack', 'untyped', 4)], note: 'its Dex is 0 (−5 AC), and you can coup de grace it' },
  { id: 'target-prone', name: 'Target is prone', group: 'combat', bonuses: () => [b('melee-attack', 'untyped', 4), b('ranged-attack', 'untyped', -4)] },
  { id: 'target-kneeling', name: 'Target is kneeling or sitting', group: 'combat', bonuses: () => [b('melee-attack', 'untyped', 2), b('ranged-attack', 'untyped', -2)] },
  { id: 'target-pinned', name: 'Target is pinned', group: 'combat', bonuses: () => [b('attack', 'untyped', 4)], note: 'it also loses its Dex bonus to AC' },
  { id: 'target-stunned', name: 'Target is stunned, blinded or cowering', group: 'combat', bonuses: () => [b('attack', 'untyped', 2)], note: 'it also loses its Dex bonus to AC' },
  { id: 'target-squeezing', name: 'Target is squeezing', group: 'combat', bonuses: () => [b('attack', 'untyped', 4)] },
  { id: 'target-charging', name: 'Target is charging', group: 'combat', bonuses: () => [b('attack', 'untyped', 2)] },

  // ---------------- The rest of the Core Rulebook conditions ----------------
  { id: 'bleed', name: 'Bleed', group: 'condition', bonuses: () => [], note: 'you take the bleed damage at the start of your turn until healed (DC 15 Heal)' },
  { id: 'broken', name: 'Broken (item)', group: 'condition', bonuses: () => [], note: 'a broken weapon −2 on attack and damage; broken armor gives half its AC and doubles its check penalty' },
  { id: 'confused', name: 'Confused', group: 'condition', bonuses: () => [], note: 'roll d% each round for what you do' },
  { id: 'dead', name: 'Dead', group: 'condition', bonuses: () => [], note: 'at negative hit points equal to your Constitution score' },
  { id: 'disabled', name: 'Disabled', group: 'condition', bonuses: () => [], note: 'at exactly 0 hit points: one move or standard action a turn; a standard action deals 1 damage' },
  { id: 'dying', name: 'Dying', group: 'condition', flags: ['noDexAc'], bonuses: () => [], note: 'unconscious; DC 10 Constitution check each round to stabilize' },
  { id: 'fascinated', name: 'Fascinated', group: 'condition', bonuses: () => [], note: '−4 on skill checks made as reactions (such as Perception)' },
  { id: 'incorporeal', name: 'Incorporeal', group: 'condition', bonuses: () => [], note: 'immune to nonmagical attacks; half damage from magic ones' },
  { id: 'paralyzed', name: 'Paralyzed', group: 'condition', flags: ['noDexAc'], bonuses: () => [], note: 'Strength and Dexterity count as 0; helpless' },
  { id: 'petrified', name: 'Petrified', group: 'condition', bonuses: () => [], note: 'turned to stone and unconscious' },
  { id: 'stable', name: 'Stable', group: 'condition', bonuses: () => [], note: 'no longer dying, but unconscious' },
  { id: 'unconscious', name: 'Unconscious', group: 'condition', flags: ['noDexAc'], bonuses: () => [], note: 'helpless' },
];
